DROP TABLE IF EXISTS `%TABLE_PREFIX%488_articles`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%488_categories`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%488_comments`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%488_observer`;