<?php

/**
 * Copyright (c) 2010, mediastuttgart werbeagentur, http://www.mediastuttgart.de
 *
 * Diese Datei steht unter der MIT-Lizenz. Der Lizenztext befindet sich in der
 * beiliegenden Lizenz Datei. Alternativ kann der Lizenztext auch unter
 * folgenden Web-Adressen eingesehen werden.
 *
 * http://www.opensource.org/licenses/mit-license.php
 * http://de.wikipedia.org/wiki/MIT-Lizenz
 */

?>
<div class="rex-toolbar">
  <div class="rex-toolbar-content">
    <a href="#" rel="data" onclick="Rexblog.Article.ToggleExtraSettings(this, event);">Metadaten</a>&nbsp;|&nbsp;
    <a href="#" rel="trackbacks" onclick="Rexblog.Article.ToggleExtraSettings(this, event);">Trackbacks</a>&nbsp;|&nbsp;
    <a href="#" rel="tags" onclick="Rexblog.Article.ToggleExtraSettings(this, event);">Schlagwörter </a>&nbsp;|&nbsp;
    <a href="#" rel="settings" onclick="Rexblog.Article.ToggleExtraSettings(this, event);">Einstellungen</a>
  </div>
</div>

<div class="rex-addon-output-v2">

  <div class="rex-message rex488-validate-message">
    <div class="rex-warning">
      <p><span>Der Artikel konnte nicht gespeichert werden. Es fehlen Pflichtangaben.</span></p>
    </div>
  </div>

  <div class="rex-form">

    <form action="index.php?page=rexblog&subpage=articles" method="post" id="rex488-form-articles">
      <fieldset class="rex-form-col-1">

        <input type="hidden" name="page" value="rexblog" />
        <input type="hidden" name="subpage" value="articles" />
        <input type="hidden" name="id" value="<?php echo rex_request('id', 'int'); ?>" />
        <input type="hidden" name="func" value="write" />
        <input type="hidden" name="mode" value="update" />

        <div class="rex-form-wrapper">

          <div class="rex488_meta_data rex488_extra_settings">

            <div class="rex-content-editmode-module-name">
              <h3 class="rex-hl4">Permanent Link</h3>
            </div>
            <div class="rex488-form-row">
              <p class="rex488-form-text">
                <input id="_rex488_permanent_link_readonly" name="_rex488_permanent_link_readonly" type="text" readonly="readonly" class="rex488-form-text" value="<?php echo htmlspecialchars($article['article_permlink']); ?>.html" />
                <input id="_rex488_permanent_link" name="_rex488_permanent_link" type="text" class="rex488-form-text" value="<?php echo htmlspecialchars($article['article_permlink']); ?>" />
              </p>
            </div>

            <div class="rex-content-editmode-module-name">
              <h3 class="rex-hl4">Suchbegriffe</h3>
            </div>
            <div class="rex488-form-row">
              <p class="rex488-form-textarea">
                <textarea id="_rex488_metadata_keywords" name="_rex488_metadata_keywords" class="rex488-form-textarea" rows="5" cols="10"><?php echo htmlspecialchars($article['keywords']); ?></textarea>
              </p>
            </div>

            <div class="rex-content-editmode-module-name">
              <h3 class="rex-hl4">Beschreibung</h3>
            </div>
            <div class="rex488-form-row">
              <p class="rex488-form-textarea">
                <textarea id="_rex488_metadata_description" name="_rex488_metadata_description" class="rex488-form-textarea" rows="5" cols="10"><?php echo htmlspecialchars($article['description']); ?></textarea>
              </p>
            </div>

          </div>

          <div class="rex488_meta_trackbacks rex488_extra_settings">

            <div class="rex-content-editmode-module-name">
              <h3 class="rex-hl4">Trackbacks</h3>
            </div>
            <div class="rex488-form-row">
              <p class="rex488-form-textarea">
                <textarea id="rex488_meta_trackbacks" name="rex488_meta_trackbacks" class="rex488-form-textarea" rows="5" cols="10"><?php echo htmlspecialchars($article['article_trackbacks']); ?></textarea>
                <span class="rex488-form-notice">Trackbacks müssen durch Leerzeichen getrennt werden.</span>
              </p>
            </div>

          </div>

          <div class="rex488_meta_tags rex488_extra_settings">

            <div class="rex-content-editmode-module-name">
              <h3 class="rex-hl4">Schlagwörter</h3>
            </div>
            <div class="rex488-form-row">
              <p class="rex488-form-textarea">
                <textarea id="rex488_meta_tags" name="rex488_meta_tags" class="rex488-form-textarea" rows="5" cols="10"><?php echo htmlspecialchars($article['article_tags']); ?></textarea>
                <span class="rex488-form-notice">Schlagwörter müssen durch Leerzeichen getrennt werden.</span>
              </p>
            </div>

          </div>

          <div class="rex488_meta_settings rex488_extra_settings">

            <div class="rex-content-editmode-module-name">
              <h3 class="rex-hl4">Einstellungen</h3>
            </div>
            <div class="rex488-form-row">
              <p class="rex488-form-select">
                <label class="rex488-form-label rex488-form-first">Kommentare zulassen</label>
                <select name="_rex488_meta_settings[comments]" size="1" class="rex488-form-select">
                  <option value="">----------------------------  Einstellung</option>
                  <option value="1"<?php if($article_meta_settings['comments'] == '1') echo ' selected="selected"'; ?>>Kommentare zulassen</option>
                  <option value="0"<?php if($article_meta_settings['comments'] == '0') echo ' selected="selected"'; ?>>Kommentare nicht zulassen</option>
               </select>
                <label class="rex488-form-label">Trackbacks zulassen</label>
                <select name="_rex488_meta_settings[trackbacks]" size="1" class="rex488-form-select">
                  <option value="">----------------------------  Einstellung</option>
                  <option value="1"<?php if($article_meta_settings['trackbacks'] == '1') echo ' selected="selected"'; ?>>Trackbacks zulassen</option>
                  <option value="0"<?php if($article_meta_settings['trackbacks'] == '0') echo ' selected="selected"'; ?>>Trackbacks nicht zulassen</option>
                </select>
              </p>
            </div>

          </div>

          <!-- article title -->
          <div class="rex-content-editmode-module-name">
            <h3 class="rex-hl4">Schlagzeile</h3>
          </div>
          <div class="rex488-form-row">
            <p class="rex488-form-text">
              <input id="title" name="title" type="text" class="rex488-form-text" value="<?php echo htmlspecialchars($article['title']); ?>" />
            </p>
          </div>
          <!-- /article title -->

          <!-- category selector -->
          <div class="rex-content-editmode-module-name">
            <h3 class="rex-hl4">Kategorien</h3>
          </div>
          <div class="rex488-form-row">
            <p class="rex-form-col-a rex488-form-select">
              <select name="rex488_article_categories[]" multiple="multiple" size="10" class="rex488-form-select" id="rex488_article_categories">
                <?php
                
                $categories_tree     = _rex488_BackendCategories::read_category_tree();
                $categories_selected = explode(',', $article['categories']);

                foreach($categories_tree as $category_id => $title)
                {
                  $selected = in_array($category_id, $categories_selected) ? ' selected="selected"' : '';
                  echo '<option value="' . $category_id . '"' . $selected .' name="category_id">' . htmlspecialchars($title) . '</option>';
                }

                ?>
             </select>
            </p>
          </div>
          <!-- /category selector -->

          <!-- plugin selector -->
          <div class="rex488-form-row rex488-form-plugin-select">
            <p class="rex-form-col-a rex488-form-select rex488-form-plugin-select">
              <select name="_rex488_content_plugins" size="1" class="rex488-form-select" onchange="Rexblog.Article.AddSlice(this); return false;" id="_rex488_content_plugins">
                <option value="">----------------------------  Plugin hinzufügen</option>
                <?php

                $content_plugins = _rex488_read_content_plugins();

                foreach($content_plugins as $id => $name)
                {
                  echo '<option value="' . $id . '" name="content_plugin_type">' . htmlspecialchars($name) . '</option>';
                }

                ?>
              </select>
            </p>
          </div>
          <!-- /plugin selector -->

          <?php

          _rex488_BackendArticles::load($article['id']);
          
          ?>

          <!-- form actions -->
          <div class="rex488-form-row rex488-form-submit">
            <p class="rex488-form-submit">
              <input type="submit" name="submit" class="rex-form-submit submit" value="Speichern" />
              <input type="submit" name="update" class="rex-form-submit update" value="Übernehmen" />
              <input type="submit" name="cancel" class="rex-form-submit cancel" value="Abbrechen" />
            </p>
          </div>
          <!-- /form actions -->

        </div>
      </fieldset>
    </form>
  </div>
</div>