<div class="_rex488_comment" id="comment-<?php echo _rex488_the_comment_id(); ?>">
  <h2><a href="<?php echo _rex488_the_comment_website(); ?>"><?php echo _rex488_the_comment_author(); ?></a> schrieb am <?php echo _rex488_the_comment_date('d.m.Y'); ?> um <?php echo _rex488_the_comment_date('H:i'); ?> Uhr folgenden Kommentar</h2>
  <div class="clearfix"></div>
  <hr noshade="noshade">
  <p><?php echo _rex488_the_comment_comment(); ?></p>
</div>
<div class="clearfix"></div>