<?php

///////////////////////////////////////////////////////////////////////////
// load settings for this article

$article_settings = _rex488_the_article_settings();

///////////////////////////////////////////////////////////////////////////
// handle article settings

$article_settings['comments']   = ($article_settings['comments'] == "1") ? 'zugelassen' : 'nicht zugelassen';
$article_settings['trackbacks'] = ($article_settings['trackbacks'] == "1") ? 'zugelassen' : 'nicht zugelassen';

///////////////////////////////////////////////////////////////////////////
// handle article output

if(_rex488_is_category())
{

?>
<div class="_rex488_article_overview">
  <h1><a href="<?php echo _rex488_the_article_permlink(); ?>"><?php echo _rex488_the_article_title(); ?></a></h1>
  <p class="permlink"><b>Permanent Link</b> <?php echo _rex488_the_article_permlink(); ?></p>
    <?php echo _rex488_the_article_excerpt(); ?>
  <p>Geposted am <?php echo _rex488_the_article_date('d.m.Y'); ?> um <?php echo _rex488_the_article_date('H:i'); ?> Uhr von <?php echo _rex488_the_article_user(); ?></p>
  <p>
    Kommentare sind <b><?php echo $article_settings['comments']; ?></b><br />
    Trackbacks sind <b><?php echo $article_settings['trackbacks']; ?></b>
  </p>
</div>
<?php

} else if(_rex488_is_article())
{

?>
<div class="_rex488_article_details">
  <h1><a href="<?php echo _rex488_the_article_permlink(); ?>"><?php echo _rex488_the_article_title(); ?></a></h1>
  <p class="permlink"><b>Permanent Link</b> <?php echo _rex488_the_article_permlink(); ?></p>
  <?php echo _rex488_the_article_post(); ?>
  <p>Geposted am <?php echo _rex488_the_article_date('d.m.Y'); ?> um <?php echo _rex488_the_article_date('H:i'); ?> Uhr von <?php echo _rex488_the_article_user(); ?></p>
  <p>
    Kommentare sind <b><?php echo $article_settings['comments']; ?></b><br />
    Trackbacks sind <b><?php echo $article_settings['trackbacks']; ?></b>
  </p>
</div>
<?php

}

?>