<?php

/**
 * Copyright (c) 2010, mediastuttgart werbeagentur, http://www.mediastuttgart.de
 *
 * Diese Datei steht unter der MIT-Lizenz. Der Lizenztext befindet sich in der
 * beiliegenden Lizenz Datei. Alternativ kann der Lizenztext auch unter
 * folgenden Web-Adressen eingesehen werden.
 *
 * http://www.opensource.org/licenses/mit-license.php
 * http://de.wikipedia.org/wiki/MIT-Lizenz
 */

?>
<div class="rex488_meta_tags rex488_extra_settings">
  <div class="rex-content-editmode-module-name">
    <h3 class="rex-hl4">Schlagwörter</h3>
  </div>
  <div class="rex488-form-row">
    <p class="rex488-form-textarea">
      <textarea id="rex717_meta_tags" name="rex717_meta_tags" class="rex488-form-textarea" rows="5" cols="10"><?php echo htmlspecialchars(_rex717_read_tab_content()); ?></textarea>
      <span class="rex488-form-notice">Schlagwörter müssen durch Leerzeichen getrennt werden.</span>
    </p>
  </div>
</div>